### ISSUE TITLE
With GDK_SCALE=2, trigger cannot be dragged

### ISSUE THREAD

**Issue by whitequark** [azonenberg/scopehal-apps#255]
Also it seems like both the trigger arrow and the vertical axis labels are drawn at 1/2 scale.

You probably want to handle this by querying `gtkWindow.get_scale_factor();`.

**Comment by azonenberg** [comment]
This was a bit harder than I expected because GTK automatically sets scaling for the default Cairo context, but OpenGL rendering isn't affected by scaling. And off-screen Cairo contexts created for render-to-texture don't have the scaling automagically applied.

This should work, please test and close the issue if fixed.
